### ISSUE TITLE
Unable to run migrations and config files

### ISSUE THREAD

**Issue by adistoica** [spatie/interactive-slack-notification-channel#1]
Hello @freekmurze !

Thank you for creating this package. I'm trying to install it, but after running: 
`php artisan vendor:publish --provider="Spatie\InteractiveSlackNotificationChannel\SlackApiNotificationChannelServiceProvider" --tag="migrations"`

or 

`php artisan vendor:publish --provider="Spatie\InteractiveSlackNotificationChannel\SlackApiNotificationChannelServiceProvider" --tag="config"`

I'm getting **Unable to locate publishable resources. Publishing complete.** and none of the resources get published.

Is there something I'm missing or doing wrong?

**Comment by freekmurze** [comment]
The class name is wrong, I've updated the readme with the right class name.

Please bear in mind that the readme is not finished yet, and we recommend only using this package if you're already familiar with Laravel's notification system and the Slack API.

**Comment by adistoica** [comment]
Thanks for the quick fix. I know my way with the Laravel's notifications and Slack API, I've already implemented the Slack app installation and authorization part, now I just need to make use of the "xobx.." token to send messages using your package.

I've tried running
```
php artisan vendor:publish --provider="Spatie\InteractiveSlackNotificationChannel
\InteractiveSlackNotificationChannelServiceProvider" --tag="migrations"
``` but I still get the same error as above. I also checked the namespace and class name and they seem to be correct in the package.

**Comment by freekmurze** [comment]
Ah lol, this package doesn't have any migrations or config file 🙂 I've just removed that section from our readme.

Yeah, the readme still needs to be polished. If you feel up to it, I would be very grateful for a PR that adds a section on the Slack app installation and authorization, and how you get the token initially. Basically the equivalent of this in another package: https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics

If would be grateful if you could PR such as section, but don't feel obliged in any way.

**Comment by adistoica** [comment]
Yup, I'll submit a PR in the following days.

I'll try a dry run to see if I can get it working :)

**Comment by freekmurze** [comment]
Cool thanks! 

I aim to polish this package a little bit more, but I'm short on time. You making that PR will motivate me some more to push through here.

Rest assured that the code is working. Using it myself to power the notifications at https://ohdear.app
